import streamlit as st
from transformers import pipeline, set_seed

# Load GPT-2 model for text generation
generator = pipeline('text-generation', model='gpt2')
set_seed(42)  # Optional: Make outputs reproducible

# Streamlit UI
st.title("AI Quote Generator 📝")
st.write("Enter a topic below and get motivational quotes generated by AI!")

topic = st.text_input("Enter a topic for your quote:")

if st.button("Generate Quotes"):
    if topic.strip() == "":
        st.warning("⚠️ Please enter a topic.")
    else:
        st.write("Here are some quotes:")
        # Generate 3 quotes
        results = generator(
            f"A motivational quote about {topic}:", 
            max_length=50, 
            num_return_sequences=3
        )
        for idx, result in enumerate(results):
            st.success(f"**Quote {idx+1}:** {result['generated_text']}")
